### ISSUE TITLE
Using data and config outside of docker

### ISSUE THREAD

**Issue by notflip** [tractr/directus-sync#19]
Thanks for this plugin! I'm trying to set it up so that I can add the data to my repository. What I've tried to do is share a folder with the docker container, and add the config to that folder, but I'm getting `Missing option directusEmail`, is my approach wrong?

Added directus-sync folder to my volumes
```
  directus:
    build: 
      context: ./ 
    restart: unless-stopped
    ports:
      - "8055:8055"
    volumes:
      - ./directus-sync:/directus-sync
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
```

Inside the directus-sync folder is the directus-sync.config.js file

I'm running the command inside my docker container using `docker exec -ti directus-docker-directus-1 npx directus-sync diff -c ./directus-sync/directus-sync.config.js`

Thanks!

**Comment by notflip** [comment]
## Update

Managed to get it working binding the volume to the correct folder (/directus)

```
  directus:
    build: 
      context: ./ 
    restart: unless-stopped
    ports:
      - "8055:8055"
    volumes:
      - ./directus-sync:/directus/directus-sync
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
```

I also copied over the config file in my Dockerfile (npm was throwing an error with the package.json so I had to name the config file using the .cjs extension)

```
RUN pnpm install directus-extension-sync
COPY directus-sync.config.cjs /directus
```

Now I have a pull, with the files being synced to my host machine using 

```
docker exec -ti directus-docker-directus-1 npx directus-sync pull -c directus-sync.config.cjs
```
